### PR TITLE
add sliver page

### PR DESCRIPTION
**Pull request by mcz9mm**
Issue: #1

### CODE REVIEW

**Review by mafreud — CHANGES_REQUESTED** [review]
Thank you for your contribution 😄 
I forgot to add sliver widgets though they are so popular in Flutter 🤣 
Btw, could you change some codes for better UX?
- split sliver_page.dart into separate 2 sections, sliver_app_bar_page.dart and sliver_list_and_sliver_gridview_page.dart
- in sliver_app_bar_page.dart, would you add some parameters, as described in it's tutorial video, like streach or onStreachTrigger?
- Would you move Sliver section to the top of list because widgets are ordered by it's adding date  

Best regards

**Comment by mcz9mm** [comment]
The following modifications have been made to improve UX.

1. I placed SliverPage on HomePage. Enabled to transition from SliverPage to SliverAppBarPage and SliverListAndSliverGridViewPage.
2. SliverAppBarPage provides parameters for stretch and onStretchTrigger, and FlexibleSpaceBar allows you to edit stretchModes.
3. In HomePage, I modified SliverSection to the top.

**Comment by mcz9mm** [comment]
## Gif🎥
May-02-2021 19-57-09

**Review by mafreud — APPROVED** [review]
LGTM 🎉

**Pull request merged**
